apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-service
  namespace: todo-app
  labels:
    app: users-service
  annotations:
    ad.datadoghq.com/users-service.logs: '[{"source":"nodejs","service":"users-service"}]'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-service
  template:
    metadata:
      labels:
        app: users-service
    spec:
      containers:
        - name: users-service
          image: abdallahrdf/users-service
          ports:
            - containerPort: 3001
          env:
            - name: PORT
              value: "3001"
            - name: MONGODB_CONNECTION_STRING
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: MONGODB_CONNECTION_STRING
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: JWT_SECRET
          imagePullPolicy: IfNotPresent                  