apiVersion: v1
kind: Service
metadata:
  name: users-service
  namespace: todo-app
  labels:
    app: users-service
spec:
  selector:
    app: users-service
  ports:
    - port: 3001
      targetPort: 3001
  type: ClusterIP
