apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
  namespace: todo-app
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/mongodb-data"
  persistentVolumeReclaimPolicy: Retain  # Keep data after PVC deletion