apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: todo-app
data:
  MONGODB_CONNECTION_STRING: mongodb://mongodb.todo-app.svc.cluster.local:27017/todo-db
  USERS_SERVICE_URL: http://users-service:3001
  TASKS_SERVICE_URL: http://tasks-service:3002