apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: todo-app
  labels:
    app: api-gateway
  annotations:
    ad.datadoghq.com/api-gateway.logs: '[{"source":"nodejs","service":"api-gateway"}]'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: abdallahrdf/api-gateway:v1.1.0
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: USERS_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: USERS_SERVICE_URL
            - name: TASKS_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: TASKS_SERVICE_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: JWT_SECRET
          imagePullPolicy: IfNotPresent
