apiVersion: v1
kind: Service
metadata:
  name: tasks-service
  namespace: todo-app
  labels:
    app: tasks-service
spec:
  selector:
    app: tasks-service
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
  type: ClusterIP
